name: terraform

on:
  push:
    branches: [ develop, main ]

jobs:
  terraform:
    runs-on: aws
    strategy:
      matrix:
        environment: [dev, staging, prod]
        include:
          - environment: dev
            tfvar_file: "dev/dev.tfvars"
            backend_file: "dev/s3.tfbackend"

          - environment: staging
            tfvar_file: "staging/staging.tfvars"
            backend_file: "staging/s3.tfbackend"

          - environment: prod
            tfvar_file: "prod/prod.tfvars"
            backend_file: "prod/s3.tfbackend"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Init
        run: terraform -chdir=terraform init -backend-config=${{ matrix.backend_file }}

      - name: Apply changes
        if: (github.ref == 'refs/heads/develop' && matrix.environment != 'prod') ||
            (github.ref == 'refs/heads/main' && matrix.environment == 'prod')
        run: terraform -chdir=terraform apply -auto-approve --var-file=${{ matrix.tfvar_file }}