name: terraform

on:
  push:
    branches: [ develop, main ]

jobs:
  terraform:
    runs-on: aws
    strategy:
      matrix:
        environment: [dev, staging, prod]
        include:
          - environment: dev
            tfvar_file: "dev/.tfvars"
            backend_file: "dev/.tfbackend"

          - environment: staging
            tfvar_file: "staging/.tfvars"
            backend_file: "staging/.tfbackend"

          - environment: prod
            tfvar_file: "prod/.tfvars"
            backend_file: "prod/.tfbackend"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Init
        run: terraform -chdir=terraform init -backend-config=${{ matrix.backend_file }}

      - name: Apply changes
        if: (github.ref == 'refs/heads/develop' && matrix.environment != 'prod') ||
            (github.ref == 'refs/heads/main' && matrix.environment == 'prod')
        run: terraform -chdir=terraform apply -auto-approve --var-file=${{ matrix.tfvar_file }} -var=environment=${{ matrix.environment }} -var=namespace=${{ vars.DOCKERHUB_USERNAME }}